[package]
name = "icfp2020"
version = "0.1.0"
authors = ["Hayato Ito <hayatoito@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
anyhow = "1.0.31"
